apiVersion: v1
kind: Secret
metadata:
  name: order-notify-secrets
  namespace: order-notify
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "changeme-local-dev"
  MYSQL_PASSWORD: "changeme-local-dev"
  RABBITMQ_MANAGEMENT_URL: "http://guest:guest@rabbitmq.order-notify.svc.cluster.local:15672/"
